// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcLOt7CwouTcr_CAKwq97tL74to0W067I',
    appId: '1:41940751026:web:7857ae4d1e4b5e2d9e6fab',
    messagingSenderId: '41940751026',
    projectId: 'flutter-8cbf8',
    authDomain: 'flutter-8cbf8.firebaseapp.com',
    databaseURL: 'https://flutter-8cbf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-8cbf8.appspot.com',
    measurementId: 'G-TJ6GC3YC4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA50342ud3x2CHhNgSWgidg-AbBmqyKLxQ',
    appId: '1:41940751026:android:80253d538c5fc9479e6fab',
    messagingSenderId: '41940751026',
    projectId: 'flutter-8cbf8',
    databaseURL: 'https://flutter-8cbf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-8cbf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcv_lH8lX8yKEXn7apL59myrqlpifwAg8',
    appId: '1:41940751026:ios:93bf622a818ecd119e6fab',
    messagingSenderId: '41940751026',
    projectId: 'flutter-8cbf8',
    databaseURL: 'https://flutter-8cbf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-8cbf8.appspot.com',
    iosClientId: '41940751026-oga557ggg16gtvbeei2f5228pvurpf7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcv_lH8lX8yKEXn7apL59myrqlpifwAg8',
    appId: '1:41940751026:ios:93bf622a818ecd119e6fab',
    messagingSenderId: '41940751026',
    projectId: 'flutter-8cbf8',
    databaseURL: 'https://flutter-8cbf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-8cbf8.appspot.com',
    iosClientId: '41940751026-oga557ggg16gtvbeei2f5228pvurpf7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
